/**
 * Bulk Upload Configuration
 * Defines all available bulk upload features with their fields and properties
 */

export const BULK_UPLOAD_FEATURES = {
  batches: {
    id: 'batches',
    label: 'Batches',
    description: 'Upload multiple batches in bulk',
    endpoint: '/internal/bulk/batches',
    dataKey: 'batches',
    icon: 'FiBox',
    status: 'active', // active, coming_soon, planned
    fields: {
      productId: {
        label: 'Product ID',
        type: 'number',
        required: true,
        description: 'The ID of the product',
        example: '1',
      },
      batchCode: {
        label: 'Batch Code',
        type: 'text',
        required: true,
        description: 'Unique batch identifier',
        example: 'B-001',
      },
      purchaseDate: {
        label: 'Purchase Date',
        type: 'date',
        required: true,
        description: 'Date of purchase (YYYY-MM-DD)',
        example: '2025-01-01',
      },
      quantity: {
        label: 'Quantity',
        type: 'number',
        required: true,
        description: 'Total quantity in batch',
        example: '100',
      },
      remainingQuantity: {
        label: 'Remaining Quantity',
        type: 'number',
        required: true,
        description: 'Available quantity (must be ≤ quantity)',
        example: '100',
      },
      unitCost: {
        label: 'Unit Cost',
        type: 'number',
        required: true,
        description: 'Cost per unit',
        example: '10.50',
      },
      warehouseId: {
        label: 'Warehouse ID',
        type: 'number',
        required: true,
        description: 'The warehouse where batch is stored',
        example: '3',
      },
      supplierId: {
        label: 'Supplier ID',
        type: 'number',
        required: false,
        description: 'The supplier of the batch',
        example: '2',
      },
      expiryDate: {
        label: 'Expiry Date',
        type: 'date',
        required: false,
        description: 'Expiry date (YYYY-MM-DD)',
        example: '2026-01-01',
      },
      remarks: {
        label: 'Remarks',
        type: 'text',
        required: false,
        description: 'Additional notes about the batch',
        example: 'Initial stock shipment',
      },
      isActive: {
        label: 'Is Active',
        type: 'boolean',
        required: false,
        description: 'Whether batch is active (true/false)',
        example: 'true',
      },
    },
  },

  products: {
    id: 'products',
    label: 'Products',
    description: 'Upload multiple products in bulk',
    endpoint: '/internal/bulk/products',
    dataKey: 'products',
    icon: 'FiList',
    status: 'active',
    fields: {
      name: {
        label: 'Product Name',
        type: 'text',
        required: true,
        description: 'Name of the product',
        example: 'Nike Running Shoes',
      },
      description: {
        label: 'Description',
        type: 'text',
        required: false,
        description: 'Product description',
        example: 'Lightweight running shoes with breathable mesh',
      },
      categoryId: {
        label: 'Category ID',
        type: 'number',
        required: false,
        description: 'Product category',
        example: '1',
      },
      manufacturer: {
        label: 'Manufacturer',
        type: 'text',
        required: true,
        description: 'Name of the manufacturer',
        example: 'Nike',
      },
      brand: {
        label: 'Brand',
        type: 'text',
        required: false,
        description: 'Product brand',
        example: 'Nike',
      },
      barcode: {
        label: 'Barcode',
        type: 'text',
        required: false,
        description: 'Product barcode (must be unique)',
        example: '123456789012',
      },
      hsn: {
        label: 'HSN Code',
        type: 'text',
        required: false,
        description: 'Harmonized System of Nomenclature code',
        example: '64041100',
      },
      upc: {
        label: 'UPC Code',
        type: 'text',
        required: false,
        description: 'Universal Product Code',
        example: '889296438745',
      },
      dimensions: {
        label: 'Dimensions',
        type: 'text',
        required: false,
        description: 'Product dimensions (e.g., 30x15x10 cm)',
        example: '30x15x10 cm',
      },
      weight: {
        label: 'Weight',
        type: 'number',
        required: false,
        description: 'Product weight in grams',
        example: '500',
      },
      unitOfMeasure: {
        label: 'Unit of Measure',
        type: 'select',
        required: false,
        options: ['pieces', 'kg', 'grams', 'liters', 'ml', 'meters', 'cm', 'boxes', 'packs'],
        description: 'Unit of measurement',
        example: 'pieces',
      },
      purchasePrice: {
        label: 'Purchase Price',
        type: 'number',
        required: true,
        description: 'Cost price per unit',
        example: '1800',
      },
      salePrice: {
        label: 'Sale Price',
        type: 'number',
        required: true,
        description: 'Selling price per unit',
        example: '2500',
      },
      unitMrp: {
        label: 'MRP',
        type: 'number',
        required: true,
        description: 'Maximum Retail Price',
        example: '2800',
      },
      reorderLevel: {
        label: 'Reorder Level',
        type: 'number',
        required: false,
        description: 'Minimum stock level to trigger reorder',
        example: '10',
      },
      maxStockLevel: {
        label: 'Max Stock Level',
        type: 'number',
        required: false,
        description: 'Maximum stock level to maintain',
        example: '100',
      },
      'taxes.cgst': {
        label: 'CGST (%)',
        type: 'number',
        required: false,
        description: 'Central Goods and Services Tax percentage',
        example: '9',
      },
      'taxes.sgst': {
        label: 'SGST (%)',
        type: 'number',
        required: false,
        description: 'State Goods and Services Tax percentage',
        example: '9',
      },
      'taxes.cess': {
        label: 'Cess (%)',
        type: 'number',
        required: false,
        description: 'Cess percentage',
        example: '0',
      },
      isActive: {
        label: 'Is Active',
        type: 'boolean',
        required: false,
        description: 'Whether product is active',
        example: 'true',
      },
    },
  },

  suppliers: {
    id: 'suppliers',
    label: 'Suppliers',
    description: 'Upload multiple suppliers in bulk',
    endpoint: '/internal/bulk/suppliers',
    dataKey: 'suppliers',
    icon: 'FiTool',
    status: 'active',
    fields: {
      name: {
        label: 'Supplier Name',
        type: 'text',
        required: true,
        description: 'Name of the supplier',
        example: 'ABC Suppliers',
      },
      businessName: {
        label: 'Business Name',
        type: 'text',
        required: false,
        description: 'Official business name',
        example: 'ABC Trading Co.',
      },
      contactPerson: {
        label: 'Contact Person',
        type: 'text',
        required: false,
        description: 'Name of the contact person',
        example: 'John Doe',
      },
      phone: {
        label: 'Phone',
        type: 'text',
        required: false,
        description: 'Primary phone number',
        example: '+911234567890',
      },
      alternatePhone: {
        label: 'Alternate Phone',
        type: 'text',
        required: false,
        description: 'Secondary phone number',
        example: '+919876543210',
      },
      email: {
        label: 'Email',
        type: 'email',
        required: false,
        description: 'Supplier email address',
        example: 'abc@example.com',
      },
      gstin: {
        label: 'GSTIN',
        type: 'text',
        required: false,
        description: 'GST Identification Number (must be unique)',
        example: '29ABCDE1234F1Z5',
      },
      rating: {
        label: 'Rating',
        type: 'number',
        required: false,
        description: 'Supplier rating (0 to 5)',
        example: '4.5',
      },
      addressLine: {
        label: 'Address',
        type: 'text',
        required: false,
        description: 'Street address',
        example: '123 Main Street',
      },
      city: {
        label: 'City',
        type: 'text',
        required: false,
        description: 'Supplier location city',
        example: 'Bengaluru',
      },
      state: {
        label: 'State',
        type: 'text',
        required: false,
        description: 'Supplier location state',
        example: 'Karnataka',
      },
      pinCode: {
        label: 'Pin Code',
        type: 'text',
        required: false,
        description: 'Postal pin code',
        example: '560001',
      },
      bankAccountNumber: {
        label: 'Bank Account Number',
        type: 'text',
        required: false,
        description: 'Supplier bank account number',
        example: '1234567890123456',
      },
      ifscCode: {
        label: 'IFSC Code',
        type: 'text',
        required: false,
        description: 'Bank IFSC code',
        example: 'SBIN0001234',
      },
      upiId: {
        label: 'UPI ID',
        type: 'text',
        required: false,
        description: 'UPI identifier',
        example: 'abc@upi',
      },
      paymentTerms: {
        label: 'Payment Terms',
        type: 'text',
        required: false,
        description: 'Payment terms (e.g., Net 30)',
        example: 'Net 30',
      },
      creditLimit: {
        label: 'Credit Limit',
        type: 'number',
        required: false,
        description: 'Maximum credit amount allowed',
        example: '100000.00',
      },
      remarks: {
        label: 'Remarks',
        type: 'text',
        required: false,
        description: 'Additional notes about the supplier',
        example: 'Preferred supplier for electronics',
      },
      isActive: {
        label: 'Is Active',
        type: 'boolean',
        required: false,
        description: 'Whether supplier is active',
        example: 'true',
      },
    },
  },

  customers: {
    id: 'customers',
    label: 'Customers',
    description: 'Upload multiple customers in bulk',
    endpoint: '/internal/bulk/customers',
    dataKey: 'customers',
    icon: 'FiUsers',
    status: 'active',
    fields: {
      first_name: {
        label: 'First Name',
        type: 'text',
        required: true,
        description: 'Customer first name',
        example: 'John',
      },
      middle_name: {
        label: 'Middle Name',
        type: 'text',
        required: false,
        description: 'Customer middle name',
        example: 'A',
      },
      last_name: {
        label: 'Last Name',
        type: 'text',
        required: true,
        description: 'Customer last name',
        example: 'Doe',
      },
      email: {
        label: 'Email',
        type: 'email',
        required: true,
        description: 'Customer email address (must be unique)',
        example: 'john.doe@example.com',
      },
      phone: {
        label: 'Phone',
        type: 'text',
        required: true,
        description: 'Customer phone number',
        example: '9876543210',
      },
      password: {
        label: 'Password',
        type: 'text',
        required: true,
        description: 'Customer login password',
        example: 'Strong@123',
      },
      customer_type: {
        label: 'Customer Type',
        type: 'select',
        required: true,
        options: ['individual', 'business'],
        description: 'Type of customer',
        example: 'individual',
      },
      business_name: {
        label: 'Business Name',
        type: 'text',
        required: false,
        description: 'Name of the business (for business customers)',
        example: 'Doe Traders',
      },
      gender: {
        label: 'Gender',
        type: 'select',
        required: false,
        options: ['male', 'female', 'other', 'prefer_not_to_say'],
        description: 'Customer gender',
        example: 'prefer_not_to_say',
      },
      date_of_birth: {
        label: 'Date of Birth',
        type: 'date',
        required: false,
        description: 'Customer date of birth (YYYY-MM-DD)',
        example: '1995-06-15',
      },
      gstin: {
        label: 'GSTIN',
        type: 'text',
        required: false,
        description: 'GST Identification Number',
        example: '27AAECS1234F1ZV',
      },
      fssai_number: {
        label: 'FSSAI Number',
        type: 'text',
        required: false,
        description: 'FSSAI registration number',
        example: '12345678901234',
      },
      pan_number: {
        label: 'PAN Number',
        type: 'text',
        required: false,
        description: 'Permanent Account Number',
        example: 'AAECS1234F',
      },
      aadhar_number: {
        label: 'Aadhar Number',
        type: 'text',
        required: false,
        description: 'Aadhar ID number',
        example: '123412341234',
      },
      credit_limit: {
        label: 'Credit Limit',
        type: 'number',
        required: false,
        description: 'Maximum credit amount allowed',
        example: '50000',
      },
      loyalty_points: {
        label: 'Loyalty Points',
        type: 'number',
        required: false,
        description: 'Initial loyalty points',
        example: '100',
      },
      blacklist_reason: {
        label: 'Blacklist Reason',
        type: 'text',
        required: false,
        description: 'Reason if customer is blacklisted (leave empty if not)',
        example: '',
      },
    },
  },

  customerAddresses: {
    id: 'customerAddresses',
    label: 'Customer Addresses',
    description: 'Upload multiple customer addresses in bulk',
    endpoint: '/internal/bulk/customers/address',
    dataKey: 'addresses',
    icon: 'FiMapPin',
    status: 'active',
    fields: {
      user_id: {
        label: 'User ID',
        type: 'number',
        required: true,
        description: 'Customer user ID',
        example: '45',
      },
      label: {
        label: 'Label',
        type: 'text',
        required: false,
        description: 'Address label (e.g., Home, Office)',
        example: 'Home',
      },
      address_type: {
        label: 'Address Type',
        type: 'select',
        required: false,
        options: ['billing', 'shipping', 'other'],
        description: 'Type of address',
        example: 'shipping',
      },
      address_line1: {
        label: 'Address Line 1',
        type: 'text',
        required: true,
        description: 'Street address',
        example: '221B Baker Street',
      },
      address_line2: {
        label: 'Address Line 2',
        type: 'text',
        required: false,
        description: 'Additional address details',
        example: 'Near Central Mall',
      },
      landmark: {
        label: 'Landmark',
        type: 'text',
        required: false,
        description: 'Nearby landmark for reference',
        example: 'Opposite Metro Station',
      },
      city: {
        label: 'City',
        type: 'text',
        required: true,
        description: 'City name',
        example: 'Mumbai',
      },
      state: {
        label: 'State',
        type: 'text',
        required: true,
        description: 'State name',
        example: 'Maharashtra',
      },
      country: {
        label: 'Country',
        type: 'text',
        required: false,
        description: 'Country name',
        example: 'India',
      },
      pin_code: {
        label: 'Pin Code',
        type: 'text',
        required: true,
        description: 'Postal pin code',
        example: '400001',
      },
      contact_name: {
        label: 'Contact Name',
        type: 'text',
        required: false,
        description: 'Contact person name at this address',
        example: 'John Doe',
      },
      contact_phone: {
        label: 'Contact Phone',
        type: 'text',
        required: false,
        description: 'Contact person phone number',
        example: '9876543210',
      },
      contact_email: {
        label: 'Contact Email',
        type: 'email',
        required: false,
        description: 'Contact person email',
        example: 'john.doe@example.com',
      },
      is_default: {
        label: 'Is Default',
        type: 'boolean',
        required: false,
        description: 'Set as default address',
        example: 'true',
      },
    },
  },

  transportPartners: {
    id: 'transportPartners',
    label: 'Transport Partners',
    description: 'Upload multiple transport partners in bulk',
    endpoint: '/internal/bulk/transport-partners',
    dataKey: 'transport_partners',
    icon: 'FiTruck',
    status: 'active',
    fields: {
      name: {
        label: 'Name',
        type: 'text',
        required: true,
        description: 'Transport partner name',
        example: 'Fast Logistics',
      },
      business_name: {
        label: 'Business Name',
        type: 'text',
        required: false,
        description: 'Official business name',
        example: 'Fast Logistics Pvt Ltd',
      },
      contact_person: {
        label: 'Contact Person',
        type: 'text',
        required: false,
        description: 'Name of contact person',
        example: 'Ramesh Kumar',
      },
      phone: {
        label: 'Phone',
        type: 'text',
        required: false,
        description: 'Primary phone number',
        example: '9876543210',
      },
      alternate_phone: {
        label: 'Alternate Phone',
        type: 'text',
        required: false,
        description: 'Secondary phone number',
        example: '9123456780',
      },
      email: {
        label: 'Email',
        type: 'email',
        required: false,
        description: 'Email address',
        example: 'logistics@example.com',
      },
      address_line: {
        label: 'Address',
        type: 'text',
        required: false,
        description: 'Street address',
        example: 'Plot 22, Industrial Area',
      },
      city: {
        label: 'City',
        type: 'text',
        required: false,
        description: 'City name',
        example: 'Pune',
      },
      state: {
        label: 'State',
        type: 'text',
        required: false,
        description: 'State name',
        example: 'Maharashtra',
      },
      pin_code: {
        label: 'Pin Code',
        type: 'text',
        required: false,
        description: 'Postal pin code',
        example: '411001',
      },
      pan_number: {
        label: 'PAN Number',
        type: 'text',
        required: false,
        description: 'Permanent Account Number',
        example: 'AAECS1234F',
      },
      gst_number: {
        label: 'GST Number',
        type: 'text',
        required: false,
        description: 'GST Identification Number',
        example: '27AAECS1234F1ZV',
      },
      'vehicle_details.type': {
        label: 'Vehicle Type',
        type: 'text',
        required: false,
        description: 'Type of vehicle (e.g., Truck, Van)',
        example: 'Truck',
      },
      'vehicle_details.capacity': {
        label: 'Vehicle Capacity',
        type: 'text',
        required: false,
        description: 'Vehicle capacity (e.g., 10T)',
        example: '10T',
      },
      rate_per_km: {
        label: 'Rate Per KM',
        type: 'number',
        required: false,
        description: 'Charge per kilometer',
        example: '25',
      },
      base_rate: {
        label: 'Base Rate',
        type: 'number',
        required: false,
        description: 'Base charge for transport',
        example: '500',
      },
      is_active: {
        label: 'Is Active',
        type: 'boolean',
        required: false,
        description: 'Whether transport partner is active',
        example: 'true',
      },
    },
  },

  inventoryMovements: {
    id: 'inventoryMovements',
    label: 'Inventory Movements',
    description: 'Record multiple inventory movements in bulk',
    endpoint: '/internal/bulk/inventory-movements',
    dataKey: 'movements',
    icon: 'FiMove',
    status: 'active',
    fields: {
      warehouse_id: {
        label: 'Warehouse ID',
        type: 'number',
        required: true,
        description: 'Warehouse ID',
        example: '1',
      },
      product_id: {
        label: 'Product ID',
        type: 'number',
        required: true,
        description: 'Product ID',
        example: '101',
      },
      batch_id: {
        label: 'Batch ID',
        type: 'number',
        required: false,
        description: 'Batch ID (optional)',
        example: '55',
      },
      movement_type: {
        label: 'Movement Type',
        type: 'select',
        required: true,
        options: ['in', 'out', 'transfer_in', 'transfer_out', 'adjustment_positive', 'adjustment_negative', 'reserved', 'unreserved'],
        description: 'Type of inventory movement',
        example: 'in',
      },
      quantity: {
        label: 'Quantity',
        type: 'number',
        required: true,
        description: 'Quantity moved',
        example: '25',
      },
      unit_cost: {
        label: 'Unit Cost',
        type: 'number',
        required: false,
        description: 'Cost per unit',
        example: '120.5',
      },
      reference: {
        label: 'Reference',
        type: 'text',
        required: false,
        description: 'Reference number (e.g., PO number)',
        example: 'PO-2024-0098',
      },
      transaction_id: {
        label: 'Transaction ID',
        type: 'text',
        required: false,
        description: 'Transaction ID (auto-generated if omitted)',
        example: 'TXN-170000112233',
      },
      remarks: {
        label: 'Remarks',
        type: 'text',
        required: false,
        description: 'Additional remarks',
        example: 'Initial stock inward',
      },
    },
  },

  warehouses: {
    id: 'warehouses',
    label: 'Warehouses',
    description: 'Upload multiple warehouses in bulk',
    endpoint: '/internal/bulk/warehouses',
    dataKey: 'warehouses',
    icon: 'FiHome',
    status: 'active',
    fields: {
      warehouseName: {
        label: 'Warehouse Name',
        type: 'text',
        required: true,
        description: 'Name of the warehouse',
        example: 'Main Warehouse',
      },
      city: {
        label: 'City',
        type: 'text',
        required: true,
        description: 'Warehouse location city',
        example: 'Mumbai',
      },
      address: {
        label: 'Address',
        type: 'text',
        required: false,
        description: 'Full address of the warehouse',
        example: '123 Industrial Park, Mumbai',
      },
      contactPerson: {
        label: 'Contact Person',
        type: 'text',
        required: false,
        description: 'Name of warehouse manager',
        example: 'Raj Kumar',
      },
    },
  },

  promotionalOffers: {
    id: 'promotionalOffers',
    label: 'Promotional Offers',
    description: 'Upload multiple promotional offers in bulk',
    endpoint: '/internal/bulk/promotional-offers',
    dataKey: 'promotional_offers',
    icon: 'FiTag',
    status: 'active',
    fields: {
      name: {
        label: 'Offer Name',
        type: 'text',
        required: true,
        description: 'Name of the promotional offer',
        example: 'New Year Sale',
      },
      description: {
        label: 'Description',
        type: 'text',
        required: false,
        description: 'Description of the offer',
        example: 'Flat discount on all orders',
      },
      offer_type: {
        label: 'Offer Type',
        type: 'select',
        required: true,
        options: ['product_discount', 'order_discount', 'buy_x_get_y', 'free_shipping'],
        description: 'Type of promotional offer',
        example: 'order_discount',
      },
      discount_value: {
        label: 'Discount Value',
        type: 'number',
        required: false,
        description: 'Discount amount or percentage',
        example: '20',
      },
      discount_type: {
        label: 'Discount Type',
        type: 'select',
        required: false,
        options: ['fixed', 'percentage'],
        description: 'Type of discount',
        example: 'percentage',
      },
      max_discount_amount: {
        label: 'Max Discount Amount',
        type: 'number',
        required: false,
        description: 'Maximum discount amount (for percentage discounts)',
        example: '500',
      },
      min_order_amount: {
        label: 'Min Order Amount',
        type: 'number',
        required: false,
        description: 'Minimum order amount to qualify for offer',
        example: '1000',
      },
      start_date: {
        label: 'Start Date',
        type: 'date',
        required: true,
        description: 'Offer start date (YYYY-MM-DD)',
        example: '2025-01-01',
      },
      end_date: {
        label: 'End Date',
        type: 'date',
        required: true,
        description: 'Offer end date (YYYY-MM-DD)',
        example: '2025-01-31',
      },
      is_active: {
        label: 'Is Active',
        type: 'boolean',
        required: false,
        description: 'Whether offer is active',
        example: 'true',
      },
    },
  },

  inventoryStock: {
    id: 'inventoryStock',
    label: 'Inventory Stock',
    description: 'Create multiple inventory stock records in bulk',
    endpoint: '/internal/bulk/inventory-stock',
    dataKey: 'stocks',
    icon: 'FiPackage',
    status: 'active',
    fields: {
      warehouse_id: {
        label: 'Warehouse ID',
        type: 'number',
        required: true,
        description: 'Warehouse ID',
        example: '1',
      },
      product_id: {
        label: 'Product ID',
        type: 'number',
        required: true,
        description: 'Product ID',
        example: '101',
      },
      batch_id: {
        label: 'Batch ID',
        type: 'number',
        required: false,
        description: 'Batch ID (optional)',
        example: '12',
      },
      available_quantity: {
        label: 'Available Quantity',
        type: 'number',
        required: true,
        description: 'Available stock quantity',
        example: '500',
      },
      reserved_quantity: {
        label: 'Reserved Quantity',
        type: 'number',
        required: false,
        description: 'Reserved stock quantity',
        example: '50',
      },
      last_movement_id: {
        label: 'Last Movement ID',
        type: 'number',
        required: false,
        description: 'Last inventory movement ID (optional)',
        example: '555',
      },
    },
  },

  users: {
    id: 'users',
    label: 'Users',
    description: 'Upload multiple users in bulk',
    endpoint: '/internal/bulk/users',
    dataKey: 'users',
    icon: 'FiUsers',
    status: 'active',
    fields: {
      email: {
        label: 'Email',
        type: 'email',
        required: true,
        description: 'User email address (must be unique)',
        example: 'john.doe@example.com',
      },
      password: {
        label: 'Password',
        type: 'text',
        required: true,
        description: 'Password (min 7 chars: uppercase, lowercase, digit, special char)',
        example: 'P@ssw0rd!',
      },
      username: {
        label: 'Username',
        type: 'text',
        required: false,
        description: 'Unique username',
        example: 'johndoe',
      },
      first_name: {
        label: 'First Name',
        type: 'text',
        required: true,
        description: 'User first name',
        example: 'John',
      },
      middle_name: {
        label: 'Middle Name',
        type: 'text',
        required: false,
        description: 'User middle name',
        example: 'A',
      },
      last_name: {
        label: 'Last Name',
        type: 'text',
        required: true,
        description: 'User last name',
        example: 'Doe',
      },
      phone: {
        label: 'Phone',
        type: 'text',
        required: false,
        description: 'Phone number',
        example: '+911234567890',
      },
      job_title: {
        label: 'Job Title',
        type: 'text',
        required: false,
        description: 'User job title',
        example: 'Software Engineer',
      },
      department: {
        label: 'Department',
        type: 'text',
        required: false,
        description: 'User department',
        example: 'Engineering',
      },
      avatar_url: {
        label: 'Avatar URL',
        type: 'text',
        required: false,
        description: 'Avatar image URL or local path',
        example: '/uploads/avatar123.jpg',
      },
      role: {
        label: 'Role',
        type: 'select',
        required: false,
        options: ['admin', 'manager', 'operator', 'customer'],
        description: 'User role in system',
        example: 'manager',
      },
    },
  },

  warehouses: {
    id: 'warehouses',
    label: 'Warehouses',
    description: 'Upload multiple warehouses in bulk',
    endpoint: '/internal/bulk/warehouses',
    dataKey: 'warehouses',
    icon: 'FiBox',
    status: 'active',
    fields: {
      name: {
        label: 'Warehouse Name',
        type: 'text',
        required: true,
        description: 'Name of the warehouse',
        example: 'Main Warehouse',
      },
      code: {
        label: 'Warehouse Code',
        type: 'text',
        required: true,
        description: 'Unique warehouse code (must be unique)',
        example: 'WH-MAIN',
      },
      capacity: {
        label: 'Capacity',
        type: 'number',
        required: false,
        description: 'Storage capacity in units',
        example: '5000',
      },
      addressLine: {
        label: 'Address',
        type: 'text',
        required: true,
        description: 'Street address',
        example: '123 Industrial Road',
      },
      city: {
        label: 'City',
        type: 'text',
        required: true,
        description: 'City name',
        example: 'New York',
      },
      state: {
        label: 'State',
        type: 'text',
        required: true,
        description: 'State or province',
        example: 'NY',
      },
      pinCode: {
        label: 'Pin Code',
        type: 'text',
        required: true,
        description: 'Postal code',
        example: '10001',
      },
      managerName: {
        label: 'Manager Name',
        type: 'text',
        required: false,
        description: 'Name of warehouse manager',
        example: 'John Doe',
      },
      managerPhone: {
        label: 'Manager Phone',
        type: 'text',
        required: false,
        description: 'Manager phone number',
        example: '+12345678901',
      },
      isActive: {
        label: 'Is Active',
        type: 'boolean',
        required: false,
        description: 'Whether warehouse is active',
        example: 'true',
      },
    },
  },
};

/**
 * Get all features
 */
export const getAllFeatures = () => {
  return Object.values(BULK_UPLOAD_FEATURES);
};

/**
 * Get active features only
 */
export const getActiveFeatures = () => {
  return Object.values(BULK_UPLOAD_FEATURES).filter(
    (feature) => feature.status === 'active'
  );
};

/**
 * Get feature by ID
 */
export const getFeatureById = (featureId) => {
  return BULK_UPLOAD_FEATURES[featureId];
};

/**
 * Get required fields for a feature
 */
export const getRequiredFields = (featureId) => {
  const feature = getFeatureById(featureId);
  if (!feature) return [];
  return Object.entries(feature.fields)
    .filter(([, field]) => field.required)
    .map(([key, field]) => ({ key, ...field }));
};

/**
 * Get all fields for a feature
 */
export const getAllFields = (featureId) => {
  const feature = getFeatureById(featureId);
  if (!feature) return [];
  return Object.entries(feature.fields).map(([key, field]) => ({
    key,
    ...field,
  }));
};

/**
 * Get fields by keys
 */
export const getFieldsByKeys = (featureId, fieldKeys) => {
  const feature = getFeatureById(featureId);
  if (!feature) return [];
  return fieldKeys
    .filter((key) => feature.fields[key])
    .map((key) => ({
      key,
      ...feature.fields[key],
    }));
};
